{{/* print (index .Values "argocd-apps") */}}
{{/* printf "%s" (index .Values "argocd-apps") */}}
{{/*- if not (index .Values "argocd-apps" "applications") | default dict */}}
{{- if and (not (index .Values "argocd-apps" "projects")) (not (index .Values "argocd-apps" "applications")) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ .Values.metadata.namespace }} 
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.project }}
  sources: 
  {{- range $source := .Values.spec.sources }}
  {{- if hasKey $source "helm"}}
  - helm:
    {{- if $source.helm.passCredentials }}
      passCredentials: {{ $source.helm.passCredentials }}  
    {{- end }}
      valueFiles:
      {{- range $source.helm.valueFiles }}
      - {{ . }} {{- end }}
    {{- if $source.path }}
    path: {{ $source.path }}
    {{- end }}
    repoURL: {{ $source.repoURL }}
    {{- if $source.chart }}
    chart: {{ $source.chart }}
    {{- end }}
    targetRevision: {{ $source.targetRevision }}
  {{- else }}
  - ref: {{ $source.ref }}
    repoURL: {{ $source.repoURL }}
    targetRevision: {{ $source.targetRevision }}
    {{- if $source.path }}
    path: {{$source.path }}
    {{- end }}
  {{- end }}
  {{- end }}
  syncPolicy:
    {{- if .Values.spec.syncPolicy.automated }}
    automated:
      {{/* enabled: {{ .Values.spec.syncPolicy.enabled }} # Enables automated syncing of the application, true by default */}}
      prune: {{ .Values.spec.syncPolicy.prune }} # Specifies if non-defined resources in sources should be pruned during auto-syncing, false by default
      selfHeal: {{ .Values.spec.syncPolicy.selfHeal }} # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected, false by default
      allowEmpty: {{ .Values.spec.syncPolicy.allowEmpty }} # Allows deleting all application resources during automatic syncing, false by default
    {{- end }}
    syncOptions:
    {{- if hasKey .Values.spec.syncPolicy "extraOptions" }}
    {{- range .Values.spec.syncPolicy.extraOptions }}
    - {{ . }}
    {{- end }}
    {{- end }}
    # - Validate=false # Disable resource validation, equivalent to 'kubectl apply --validate=false', true by default
    - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster
    - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan
    - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation. For timing of pruning operations if .spec.syncPolicy.automated.prune is set to true
    # - RespectIgnoreDifferences=true # When syncing changes, respect fields ignored by the ignoreDifferences configuration
    # - ApplyOutOfSyncOnly=true # Sync only out-of-sync resources, rather than applying every object in the application
    # - SkipDryRunOnMissingResource=true # Allow skip dry run on missing resource
    # - Replace=true # Argo CD will use 'kubectl replace' or 'kubectl create' command to apply changes
    # - ServerSideApply=false # Argo CD will use 'kubectl apply --server-side' command to apply changes, not relying on .metadata.annotations.kubectl.kubernetes.io/last-applied-configuration
    # - Prune=false # Not supported in .spec.syncPolicy.syncOptions, prevent objects from being pruned with .metadata.annotations.argocd.argoproj.io/sync-options: Prune=false
{{- end }}
